services:
  - type: web
    name: frontend
    env: node
    rootDir: Model2/Frontend
    buildCommand: node --max-old-space-size=2048 node_modules/vite/bin/vite.js build
    staticPublishPath: dist
    plan: free
